### ISSUE TITLE
Which tensorflow and keras are you using?

### ISSUE THREAD

**Issue by oriolorra** [jianing-sun/Mask-YOLO#2]
Hi all,

I'm using Tensorflow-gpu 1.11.0 and Keras 2.1.6, and I'm facing a lot of problem with some intern functions of Tensorflow and Keras that not exist. 

Like:
    "module 'tensorflow' has no attribute 'name_scope'"
    " 'Nonetype' object has no attribute 'image_data_format'"
    " ImportError: You need to first `import keras` in order to use `keras_applications`"

I am already using Mask-RCNN from matterport, and now, I would like to try and compare this network. Could you share with me your setup?

Thank you very much,

Oriol

**Comment by jianing-sun** [comment]
@oriolorra sorry for the delay. I just checked, I was using `tensorflow==1.9.0`, `Keras-Applications==1.0.7`, `Keras==2.2.0`
I remember I had this issue before, and it was because of the conflicts between keras-applications, keras and/or probably tensorflow. But it was something a long time ago, not sure how I exactly fixed it.  I roughly remember it was because of the mismatch or incompatibility of these packages.
