### ISSUE TITLE
module not found 'get_keras_submodule'

### ISSUE THREAD

**Issue by islamau** [jianing-sun/Mask-YOLO#6]
hey, I am running the model.py file. I keep getting error saying "ImportError: cannot import name 'get_keras_submodule'". Can you please help me out? Thank you.

**Comment by islamau** [comment]
by the way, I am running keras = 2.3.0 version and keras_applications = 1.0.8 version. Do you think the issue is due to the version?

**Comment by radheyakale** [comment]
from keras.preprocessing import keras_preprocessing
keras_preprocessing.get_keras_submodule('backend')

**Comment by impravin22** [comment]
> from keras.preprocessing import keras_preprocessing
> keras_preprocessing.get_keras_submodule('backend')

It did not work for me

**Comment by impravin22** [comment]
> hey, I am running the model.py file. I keep getting error saying "ImportError: cannot import name 'get_keras_submodule'". Can you please help me out? Thank you.

Have you found any solution for this?

**Comment by rigved** [comment]
I faced this same issue while compiling tensorflow (un-related to this project). I fixed it by installing the [Keras Preprocessing package](https://github.com/keras-team/keras-preprocessing):

```
conda install keras-preprocessing
```

Or you can install it from PyPI using `pip`.

The reason this worked is because the default `keras_preprocessing` module didn't have any implementation for the `get_keras_submodule` function. The code in it looked like it was added as a stub module. I'm not even sure how this default module was installed on my system (maybe installed by `keras` module?). But the actual `keras-preprocessing` module that I linked above has the [correct implementation](https://github.com/keras-team/keras-preprocessing/blob/5949df1c059a53d98a6004d5bfc93708e5ec6c4a/keras_preprocessing/__init__.py#L11) for the `get_keras_submodule` function.
